version: "3.8"

services:
  server:
    image:  'nginx:stable-alpine'
    ports:
     - '80:80'
    volumes :
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
    networks:
      - mynetwork
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
     - ./src:/var/www/html:delegated
     - ./src/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - mynetwork
  mysql:
   platform: linux/x86_64 
   image: mysql:8
   ports:
     - 3307:3307
   env_file:
    - ./env/mysql.env
   volumes:
    - mysql-data:/var/lib/mysql
   networks:
    - mynetwork
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    env_file:
    - ./env/phpmyadmin.env
    ports:
      - 81:80
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
volumes:
  mysql-data:
